### ISSUE TITLE
Unable to fully translate

### ISSUE THREAD

**Issue by rasmusberg** [somewherewarm/woocommerce-product-bundles-min-max-items#1]
Hi :)

I have fully translated the translations files and uploadet them in the same folder as the .pot file.

But the translation does not appear on the website. The file names are correct and I have selected my lang (Danish) in the settings of POedit.

Check for yourself here:
https://jointpapir.dk/produkt/jointpapir-og-filtertips-abonnement/

Also, I have tried to remove the "optional" string, but the "-" sign are still left to be removed. How to I remove the whole string including the "-" sign.

**Comment by franticpsyx** [comment]
Hey @rasmusberg - thanks for reporting this! 

I was able to confirm that localized textdomain data was not loaded on plugin init and pushed a commit that should resolve this. Can you please install the latest version from the `master` branch and let me know if it works for you?

Just make sure that your generated `.po`/`.mo` files are properly named (`my-plugin-{locale}.mo`) and copied into the correct directory (start with the plugin `languages` directory - you can also use the `wp-content/languages/plugins/` directory).

**Comment by rasmusberg** [comment]
Thanks for helping :)

I have named both the .po and .mo file "woocommerce-product-bundles-min-max-items-da_DK" (Danish).

The "-" sign did not go away. I have regenerated the .po and .mo files and tried both the plugins's lang-dir and the main lang-dir for plugins.

I also tried clearing cache in both WP and my browser.

**Comment by franticpsyx** [comment]
>The "-" sign did not go away. I have regenerated the .po and .mo files and tried both the plugins's lang-dir and the main lang-dir for plugins.

It sounds like this is unrelated to the "PB: Min/Max Items" mini-extension. If you need help with Product Bundles, please open a ticket with WooThemes support. Thanks!

**Comment by rasmusberg** [comment]
I did. They told me to contact you :S

**Comment by franticpsyx** [comment]
>I did. They told me to contact you :S

Regarding the issue with translating the Min/Max Items mini-extension - yes, it should be reported here since the mini-extension is not maintained or supported by WooThemes. 

By the way are the translated strings working after installing the latest version from `master`?

The 2nd issue with modifying/hiding the `optional` suffix is irrelevant to this codebase, since that string is displayed by Product Bundles itself.

Keep in mind that when opening an issue (be it on a public repository or with a support team), it is always a good idea to open separate tickets/issues for different problems you are facing, since it makes it easier to get accurate responses/help!

**Comment by rasmusberg** [comment]
Oh okay - I'll remember that for next time - thx

Yes sorry - the translations works perfectly now!

Thanks for the man! I'll contact WooThemes regarding the optional suffix

**Comment by franticpsyx** [comment]
YW - make sure you check out https://docs.woothemes.com/document/bundles/bundles-tips-tricks-and-snippets/#remove_optional_suffix before opening that ticket 👍

**Comment by rasmusberg** [comment]
Thanks - but I already have used that code. The problem is that it only removes the word "optional" and not the "-" sign...
