### ISSUE TITLE
No alert color

### ISSUE THREAD

**Issue by dydadou** [somewherewarm/woocommerce-product-bundles-min-max-items#2]
Hi,
Should the alert message be in red (or any alert color set)  when a customer exceed the authorized max quantities  ?
Mine stay in default text color (see picture below)
For the record I use product bundles (and min/max mini extension) as part of a composite product (Woo Composite Product plugin).
Thanks for your help.

![image](https://user-images.githubusercontent.com/32650175/31352829-7e278a22-ad30-11e7-9fec-87f878be3258.png)

**Comment by dydadou** [comment]
Any help ?

**Comment by franticpsyx** [comment]
Hi @dydadou -- the styling of warning messages is entirely controlled by your theme, not WC Product Bundles or Min/Max Items.

It seems like your theme is probably targeting `.woocommerce-info` elements in a way different than WC core -- it's probably also unloading WC core styles instead of overriding them.

This might be resolved for you when PB 5.5 is out. In v5.5, notice lists are wrapped in `div` element, which should resolve some edge-case issues like this.
